#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = DoomEd

PROJECTVERSION = 1.1
LANGUAGE = English

APPICON = DoomEdIcon.tiff
LOCAL_RESOURCES = DoomEd.nib FindLine.nib line.nib preferences.nib\
                  Project.nib Remapper.nib SectorEditor.nib\
                  SpecialList.nib TextLog.nib TextureEdit.nib\
                  TexturePalette.nib thing.nib ThingPalette.nib\
                  ThingStripper.nib

GLOBAL_RESOURCES = Delete.tiff DoomEdIcon.tiff DownArrow.tiff Find.tiff\
                   johnc.tiff LeftArrow.tiff Me1.tiff Me2.tiff\
                   Recycle.tiff RightArrow.tiff SmallDemon.tiff\
                   UpArrow.tiff DESave.snd D_Dbite.snd D_EPain.snd\
                   D_Ratdie.snd

CLASSES = BlockWorld.m Coordinator.m DoomProject.m EditWorld.m\
          EWDoomSave.m EWLoadSave.m FindLine.m FlatRemapper.m\
          FlatsView.m FloatingPanel.m LinePanel.m LineSpecialRemapper.m\
          MapView.m MapViewDraw.m MapViewResp.m MapWindow.m\
          PopScrollView.m PreferencePanel.m Remapper.m SectorEditor.m\
          SectorEditView.m SettingsPanel.m SpecialList.m\
          SpecialListWindow.m TextLog.m TextureEdit.m TexturePalette.m\
          TexturePalView.m TexturePatchView.m TextureRemapper.m\
          TextureView.m ThermoView.m ThingPalette.m ThingPalView.m\
          ThingPanel.m ThingRemapper.m ThingStripper.m ThingWindow.m\
          Timing.m ToolPanel.m Wadfile.m

HFILES = BlockWorld.h Coordinator.h DoomProject.h EditWorld.h\
         FindLine.h FlatRemapper.h FlatsView.h FloatingPanel.h\
         lbmfunctions.h LinePanel.h LineSpecialRemapper.h MapView.h\
         MapViewDraw.h MapViewResp.h MapWindow.h pathops.h\
         PopScrollView.h PreferencePanel.h Remapper.h R_mapdef.h\
         SectorEditor.h SectorEditView.h SettingsPanel.h SpecialList.h\
         SpecialListWindow.h TextLog.h TextureEdit.h TexturePalette.h\
         TexturePalView.h TexturePatchView.h TextureRemapper.h\
         TextureView.h ThermoView.h ThingPalette.h ThingPalView.h\
         ThingPanel.h ThingRemapper.h ThingStripper.h ThingWindow.h\
         Timing.h ToolPanel.h Wadfile.h

MFILES = DoomEd_main.m idfunctions.m lbmfunctions.m pathops.m

PSWFILES = wraps.psw

OTHERSRCS = Makefile


MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = app.make
INSTALLDIR = $(HOME)/Apps
INSTALLFLAGS = -c -s -m 755
SOURCEMODE = 444

ICONSECTIONS =	-sectcreate __ICON app DoomEdIcon.tiff

LIBS = -lMedia_s -lNeXT_s -lIndexing_s
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)


-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
